version: '2.1'

services:
  heroes-vue-node-api:
    image: heroes-vue-node-api
    build:
      context: .
      args:
        VUE_APP_API: ${VUE_APP_API}
    env_file:
      - .env
    ports:
      - 9000:9000
